// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxymA1lSxyzICo_TwbNDLvey4eJOoNHNs',
    appId: '1:634047536649:web:cd9b1ddb9af0acbdc6e2d8',
    messagingSenderId: '634047536649',
    projectId: 'bcskills-c8e3e',
    authDomain: 'bcskills-c8e3e.firebaseapp.com',
    storageBucket: 'bcskills-c8e3e.appspot.com',
    measurementId: 'G-XXQF4KR2YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEhlMSNgveUITiqk77CQ9X6n2SnXW-cpo',
    appId: '1:634047536649:android:c72edf3c84a2e281c6e2d8',
    messagingSenderId: '634047536649',
    projectId: 'bcskills-c8e3e',
    storageBucket: 'bcskills-c8e3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM4Kd8FT7Vw-x-oY74NIF-G_YImRJSfbk',
    appId: '1:634047536649:ios:16795552f43fa906c6e2d8',
    messagingSenderId: '634047536649',
    projectId: 'bcskills-c8e3e',
    storageBucket: 'bcskills-c8e3e.appspot.com',
    iosClientId: '634047536649-bu9b60hufuidicjna9nhihc9ccu8rhe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM4Kd8FT7Vw-x-oY74NIF-G_YImRJSfbk',
    appId: '1:634047536649:ios:67538d04428ece78c6e2d8',
    messagingSenderId: '634047536649',
    projectId: 'bcskills-c8e3e',
    storageBucket: 'bcskills-c8e3e.appspot.com',
    iosClientId: '634047536649-99d7j3vq9iuqovhs339msh9d9srqfk5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
